const PX_PER_CELL = 32;

const WINDOW_WIDTH_CELLS = 20;
const WINDOW_HEIGHT_CELLS = 20;

const WINDOW_WIDTH_PX = WINDOW_WIDTH_CELLS*PX_PER_CELL;
const WINDOW_HEIGHT_PX = WINDOW_HEIGHT_CELLS*PX_PER_CELL;